version: '3'

networks:
  backend:
    driver: bridge

volumes:
  mariadb:
    driver: local

services:

######################################################
# Workspace
######################################################

    workspace:
      build:
        context: docker/php-cli-5-6
      volumes:
        - ./:/var/www/html:delegated
      tty: true
      networks:
        - backend

######################################################
# Apache / PHP 5.5
######################################################

    php-apache:
      build:
        context: docker/apache-5-6
      volumes:
        - ./:/var/www/html:delegated
      ports:
        - "0.0.0.0:80:80"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - PHP_OPCACHE_REVALIDATE_FREQUENCY=0
      networks:
        - backend

######################################################
# MariaDB
######################################################

    mariadb:
      build: docker/mariadb
      volumes:
        - ./data/mariadb:/var/lib/mysql
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend
